### PR TITLE
change scenario tag filter

### PR DESCRIPTION
**Pull request by an-dr-eas-k**
Hello, not sure if you might like this PR. 

I am having trouble getting all tags listed correctly for the scenarios, so I change the filter routine for the scenario tags. 

In the current version of cucumber-html-reporter it is assumed, the feature tags are again listed in the scenarios, and addition to that, there are specific demands to the tag order of the scenarios. My change is less demanding.

I'd be happy to see that merged, thus I wouldn't need to work around the way I adjust the feature tags.

### CODE REVIEW

**Comment by gkushang** [comment]
@an-dr-eas-k - thanks for your contribution! Do you have any example screenshots that tell the difference (before and with this change)? it'd be great to visually see 🙇

**Comment by an-dr-eas-k** [comment]
Sure, thank you very much for your interest! 

here is a screenshot with the changes:
image
You see, the tags from the scenarios are shown and also you see the tags from the feature. The current implementation does not list any scenario tags.

In the current implementation, it is expected, that the scenario tags repeat the feature tags. The first scenario tags are dropped and only subsequent tags are shown. Thus, no tags are listed in my report, because my feature tags are not present for the scenarios.

My update filters the feature tags from the scenario tags by content, not by index.

**Comment by an-dr-eas-k** [comment]
Dear @gkushang please let us continue on this PR if you're still interested. Please tell me your demands and I can go ahead with further input.

**Review by gkushang — APPROVED** [review]

**Comment by gkushang** [comment]
@an-dr-eas-k apologies for delay! approved and merged, will be released soon

**Comment by gkushang** [comment]
@an-dr-eas-k - released with the version V7.1.1, thanks for contributing!

**Pull request merged**
