### PR TITLE
Adding toggle function to show/hide features by passed or failed status

### PR DESCRIPTION
**Pull request by srbarrios**
That PR intends to implement the new feature https://github.com/gkushang/cucumber-html-reporter/issues/154

Adding a toggle function that will show/hide features depending on its status. It will group only in passed and failed features.

### CODE REVIEW

**Comment by gkushang** [comment]
@srbarrios 

thank you for the PR! this is the most awaiting feature! Looking at it now ... 👍

**Comment by srbarrios** [comment]
Hi @gkushang!
Did you found something remarkable to change? It would be awesome to merge it :)

**Comment by gkushang** [comment]
thank you @srbarrios for the great contribution. merging it now!

**Comment by gkushang** [comment]
@srbarrios the toggle on bootstrap report does not work. I expect it to toggle and filter the Failed Features by clicking on the `Failed` but it does not filter. Am I doing something wrong? What is the expected behavior?


toggle-does-not-work

**Comment by srbarrios** [comment]
What it does is tag as failed the feature if some scenario of this feature is marked as failed. Then it hides/show the features tagged as failed or passed.
Let me try tomorrow morning UTC, it was working for me :/ I tell you something asap.

Thank you to look at it!

**Comment by srbarrios** [comment]
I found the problem, it was related to the use of columns.
I moved that piece of code:
```javascript
<% if (feature.scenarios.failed) { %>
<div class="feature-failed">
<% } else { %>
<div class="feature-passed">
<% } %>
```
out of the if related with rows and columns:
```javascript
<% if (featureIndex === 0 || featureIndex % 2 === 0) { %>
<div class="row" xmlns="http://www.w3.org/1999/html">
<% } %>
```

**Comment by srbarrios** [comment]
Creating a new PR. Sorry for that.

**Pull request merged**
