### PR TITLE
Add support for cucumber 3

### PR DESCRIPTION
**Pull request by mucsi96**
I extracted the report creation to separate node process as the CucumberJS report is not created yet even in new `AfterAll` hook.

### CODE REVIEW

**Comment by gkushang** [comment]
@mucsi96 thanks for this awesome update 👍 

I see some errors even though the [CI Job](https://travis-ci.org/gkushang/cucumber-html-reporter/builds/263819856?utm_source=github_status&utm_medium=notification) passes. Can you take a look?

```

npm ERR! Linux 4.8.12-040812-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v7.7.1/bin/node" "/home/travis/.nvm/versions/node/v7.7.1/bin/npm" "run" "run:cucumber"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE
npm ERR! cucumber-html-reporter@3.0.0 run:cucumber: `node node_modules/cucumber/bin/cucumber test/features/ -r test/features/step_definitions -f json:test/report/cucumber_report.json --no-strict`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cucumber-html-reporter@3.0.0 run:cucumber script 'node node_modules/cucumber/bin/cucumber test/features/ -r test/features/step_definitions -f json:test/report/cucumber_report.json --no-strict'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cucumber-html-reporter package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node_modules/cucumber/bin/cucumber test/features/ -r test/features/step_definitions -f json:test/report/cucumber_report.json --no-strict
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cucumber-html-reporter
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cucumber-html-reporter
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/gkushang/cucumber-html-reporter/npm-debug.log

```

**Comment by mucsi96** [comment]
@gkushang Thanks :) Fixed 👍

**Comment by gkushang** [comment]
looks good 👍

**Comment by gkushang** [comment]
published as v3.0.0

**Pull request merged**
