### PR TITLE
Support Cucumber Version 6

### PR DESCRIPTION
**Pull request by subhamishra**
--> Changed the json format to match the previous json format of the cucumber result.
--> and also maintain the previous version json format support.

### CODE REVIEW

**Comment by subhamishra** [comment]
@gkushang I have faced a issue when we upgraded mine cucumber to version 6. There they are generating different json format for cucumber test result so i changed some of the reporter.js code to support that version if anybody pass "cucumberVersion" attribute through the options of genrate function  and the version is greater or equal to 6 my changes will run and it will generate the report as previously it was generating.

not support:
--> if some put some embedded screenshot this will not support.

**Comment by gkushang** [comment]
@subhamishra 

Firstly, I apologize for the late response.

This is the most awaiting feature. Thank you for taking on it and submitting the PR. I think we can use https://www.npmjs.com/package/compare-versions to compare version if it's above V6. Since I took so much time to review the changes, I will look at the version compare and will release a Major Release.

🚀 👍

**Comment by gkushang** [comment]
I take the above comment back. Looking at this Cucumber.JS documentations, it seems like the JSON Formatter support is Restore back in `v6.0.3`.

@subhamishra 

can you pls verify with the latest published `cucumber-html-reporter@5.1.0` that it works fine with `cucumber@6.0.3` or above version?

**Comment by gkushang** [comment]
@subhamishra We won't need these changes as CucumberJS changed/reverted back their JSON Formatter. So closing this PR. The later version of Cucumber 6, works fine as per https://github.com/gkushang/cucumber-html-reporter/issues/202.

**Comment by subhamishra** [comment]
Hi @gkushang 

yeah it is working fine with cucumber version 6.0.3 and thanks for reply.

**Pull request closed without merging**
