### PR TITLE
Small improvements

### LINKED ISSUE #29: package.json not found
When I generate html report from a subdirectory as `cwd` I got an error message `Error: ENOENT: no such file or directory, open 'c:\Users\mucsi\repos\nightwatch-cucumber\examples\multi-example\packa
ge.json'`. Is it possible to provide the name and version using configuration object instead of reading `package.json` of the current directory?

### PR DESCRIPTION
**Pull request by mucsi96**
- Fix package.json lookup.
- Add support for inline png screenshots.
- Fix success log

Closes #29

### CODE REVIEW

**Comment by mucsi96** [comment]
Please help me to fix the build. Also if you not plan to support Node 0.12.16 we can use the find-up npm package.

**Comment by gkushang** [comment]
@mucsi96 - I suppose we should still support older version of node since few folks are still on older version. I will look at the build. Thanks!

**Comment by mucsi96** [comment]
I could fix the build. Can we merge is. Than I can use your package from https://github.com/mucsi96/nightwatch-cucumber 😃

**Comment by mucsi96** [comment]
@gkushang Can we merge this? This fill fix the lookup of the package.json if the module is not direct dependency. Also this add support for inline images

**Comment by gkushang** [comment]
Sure, merging this. Let's add a support for nightwatch screen capture in another PR.

**Comment by gkushang** [comment]
Could you explain more about inline images?

**Comment by gkushang** [comment]
@mucsi96 never mind, got it 😃 , will publish this with 0.2.18

**Comment by gkushang** [comment]
@mucsi96 published with v@0.3.0

**Comment by mucsi96** [comment]
Cool! Thanks!

**Pull request merged**
