### PR TITLE
Bootstrap theme filters

### PR DESCRIPTION
**Pull request by srbarrios**
That PR intends to implement the new feature #154

Adding a toggle function that will show/hide features depending on its status. It will group only in passed and failed features.

screen

### CODE REVIEW

**Comment by gkushang** [comment]
thanks @srbarrios for the quick PR. I will take a look

**Comment by srbarrios** [comment]
> thanks @srbarrios for the quick PR. I will take a look

Thank you!

**Comment by gkushang** [comment]
> > thanks @srbarrios for the quick PR. I will take a look
> 
> Thank you!
> 
> We already started to use your 5.0.1 version btw hehe Just had the problem Luis described :)

It should be fixed with the `5.0.2` version. pls let me know if you see any more issues.

**Comment by srbarrios** [comment]
It would be awesome to have it soon, it will be easier to review those big reports that we generate  :man_shrugging: 

image

**Comment by srbarrios** [comment]
Please :pray: take a look

**Comment by gkushang** [comment]
Apology for the late response.

**Comment by srbarrios** [comment]
Thank you! :)

**Comment by gkushang** [comment]
published with cucumber-html-reporter@5.1.0 🚀

**Pull request merged**
