### PR TITLE
feature: Update bootstrap template to 4

### PR DESCRIPTION
**Pull request by zmilonas**
image

- [x] Moved all dependencies to `cdnjs.cloudflare.com` 
- [x] Upgraded to Bootstrap 4
- [x] Improved UX and UI a little, for clarity mostly.

With this loads templating madness a move to React should be considered

### CODE REVIEW

**Comment by Ducistech** [comment]
Try to add filters if possible. For pass failed and skipped steps

**Comment by zmilonas** [comment]
As far as I tested the ones in https://github.com/gkushang/cucumber-html-reporter/pull/198 seem to work. Only problem is that the automated tests in this repo don't generate any failing scenarios :)

**Comment by gkushang** [comment]
Thank you for the nice contribution. I will look at both of your PRs in a day and will include in next major release in few days.

**Comment by gkushang** [comment]
@zmilonas 

Unfortunately, this change breaks the original design (look & feel). I see the cropped Chart as shown below. It also changes the color (black to blue) and font styling. 

Also, the `hierarchy` template is broken too (in the title and the scenario cards). Shown in another image below.

It would be great to have the original look and feel and **add** Expand and Collapse button to it? Let me know if it is possible. 

Thank you!

### Look and Feel from this change:

Screen Shot 2020-04-13 at 8 57 45 PM

hierarchy template:

Screen Shot 2020-04-13 at 9 00 38 PM

### Original Look and Feel:

Screen Shot 2020-04-13 at 9 01 03 PM

original hierarchy template:

Screen Shot 2020-04-13 at 9 00 54 PM

**Review by gkushang — CHANGES_REQUESTED** [review]
Please see the comment above regarding styling and look/feel! Thank you!

**Comment by gkushang** [comment]
closing due to inactivity! Pls reopen the PR

**Pull request closed without merging**
